all:
	gcc -o simple0 simple0.c
	gcc -o simple0_static simple0.c -static

simple0:
	gcc -o simple0 simple0.c


simple0_static:
	gcc -o simple0_static simple0.c -static

clean:
	@rm -f simple0 simple0_static
