all:
	gcc -o crackme03 crackme03.c -lpthread
	# If want to create 32bits.
	# gcc -m32 -o crackme03_32b crackme03.c -lpthread
	gcc -o crackme03_set_1 crackme03_set_1.c -lpthread
	gcc -o crackme03_set_31337 crackme03_set_31337.c -lpthread
	gcc -o crackme03_read crackme03_read.c -lpthread
